M48
; DRILL file {KiCad 8.0.8+1} date 2025-02-28T11:29:14+1100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-28T11:29:14+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8+1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X6.35Y-2.85
T2
X1.5Y-2.5
X1.55Y-5.0
X6.45Y-2.5
X6.45Y-5.0
M30
